Repository CSCfi/metadata-submitter, pull requests merged in 2020-12, with the labels that each got.

#151 registered user login access to API and resources
  docker-compose.yml
  docs/specification.yml
  metadata_backend/api/auth.py
  metadata_backend/api/handlers.py
  metadata_backend/api/middlewares.py
  metadata_backend/api/operators.py
  metadata_backend/conf/conf.py
  metadata_backend/database/db_service.py
  metadata_backend/helpers/schemas/users.json
  tests/integration/mock_auth.py
  tests/integration/run_tests.py
  tests/test_handlers.py
  tests/test_operators.py
Labels: enhancement

#164 fix folder publish draft deletion
  metadata_backend/api/handlers.py
  tests/test_handlers.py
Labels: bug

#168 Switch to using UUIDs
  metadata_backend/api/operators.py
  tests/test_operators.py
Labels: enhancement

#171 fix location header for logout redirect
  metadata_backend/api/auth.py
  metadata_backend/api/handlers.py
Labels: bug

#165 Docs/metadata project docs
  README.md
  docker-compose.yml
  docs/code.rst
  docs/deploy.rst
  docs/frontend.rst
  docs/index.rst
  docs/specification.yml
  docs/submitter.rst
  docs/test.rst
  docs/validator.rst
  metadata_backend/conf/conf.py
  metadata_backend/server.py
Labels: documentation

#169 Feature/access handler tests
  docker-compose.yml
  docs/submitter.rst
  metadata_backend/api/middlewares.py
  metadata_backend/conf/conf.py
  tests/mockups.py
  tests/test_auth.py
  tests/test_handlers.py
  tests/test_middlewares.py
Labels: enhancement

#173 Feature/add health endpoint
  metadata_backend/api/health.py
  metadata_backend/api/middlewares.py
  metadata_backend/database/db_service.py
  metadata_backend/server.py
  tests/integration/run_tests.py
  tests/test_health.py
  tests/test_server.py
Labels: enhancement

#172 Test coverage increase
  metadata_backend/api/auth.py
  metadata_backend/api/operators.py
  metadata_backend/database/db_service.py
  tests/integration/run_tests.py
  tests/mockups.py
  tests/test_auth.py
  tests/test_db_service.py
  tests/test_handlers.py
  tests/test_operators.py
  tests/test_parser.py
Labels: bug, enhancement
