Repository CSCfi/metadata-submitter, pull requests merged in 2020-06, with the labels that each got.

#29 Very small typos
  CONTRIBUTING.md
  README.md
  metadata_backend/api/parser.py
Labels: bug

#30 Feature/improve parsing
  metadata_backend/api/parser.py
  tests/api/test_parser.py
Labels: enhancement

#31 Feature/improve database
  metadata_backend/conf/__init__.py
  metadata_backend/conf/conf.py
  metadata_backend/database/db_services.py
  setup.py
  tests/database/test_db_services.py
Labels: bug, enhancement

#35 Add query endpoint functionality
  metadata_backend/api/handlers.py
  metadata_backend/api/operators.py
  metadata_backend/conf/conf.py
  metadata_backend/database/db_service.py
  metadata_backend/server.py
  tests/test_db_service.py
  tests/test_handlers.py
Labels: enhancement

#37 Create release 0.1.0
  .coveragerc
  .env
  .isort.cfg
  .travis.yml
  CONTRIBUTING.md
  Dockerfile
  README.md
  deploy/mongodb/docker-compose.yml
  metadata_backend/__init__.py
  metadata_backend/__main__.py
  metadata_backend/api/__init__.py
  metadata_backend/api/handlers.py
  metadata_backend/api/operators.py
  metadata_backend/api/views.py
  metadata_backend/conf/__init__.py
  metadata_backend/conf/conf.py
  metadata_backend/database/__init__.py
  metadata_backend/database/db_service.py
  metadata_backend/database/db_services.py
  metadata_backend/helpers/__init__.py
  metadata_backend/helpers/config.py
  metadata_backend/helpers/logger.py
  metadata_backend/helpers/parser.py
  metadata_backend/helpers/schema_load.py
  metadata_backend/helpers/schema_loader.py
  metadata_backend/helpers/schemas/EGA.dac.xsd
  metadata_backend/helpers/validator.py
  metadata_backend/server.py
  requirements.txt
  scripts/install-hooks.sh
  scripts/pre-commit.sh
  setup.py
  tests/__init__.py
  tests/conftest.py
  tests/coveralls.py
  tests/test_db_service.py
  tests/test_files/analysis/ERZ266973.xml
  tests/test_files/analysis/processed_reads_analysis.xml
  tests/test_files/analysis/reference_alignment_analysis.xml
  tests/test_files/analysis/reference_sequence_analysis.xml
  tests/test_files/analysis/sequence_assembly_analysis.xml
  tests/test_files/analysis/sequence_variation_analysis.xml
  tests/test_files/experiment/ERX000119.xml
  tests/test_files/project/PRJNA294609.xml
  tests/test_files/run/ERR000076.xml
  tests/test_files/sample/SRS001433.xml
  tests/test_files/study/SRP000539.xml
  tests/test_files/study/SRP000539_invalid.xml
  tests/test_files/submission/ERA521986_emptyhold.xml
  tests/test_files/submission/ERA521986_nodetails.xml
  tests/test_files/submission/ERA521986_valid.xml
  tests/test_files/submission/ERA521986_valid2.xml
  tests/test_handlers.py
  tests/test_parser.py
  tests/test_schema_loader.py
  tests/test_server.py
  tests/test_utils.py
  tox.ini
Labels: release

#42 Feature/add some small fixes
  CONTRIBUTING.md
  README.md
  metadata_backend/__init__.py
  metadata_backend/api/handlers.py
  tests/test_files/study/SRP000539_copy.xml
  tests/test_handlers.py
Labels: enhancement

#56 Feature/add integration tests and api fixes
  .travis.yml
  README.md
  development/Dockerfile-dev
  development/docker-compose.yml
  development/mongodb-docker/docker-compose.yml
  docker-compose.yml
  docs/specification.yml
  metadata_backend/api/handlers.py
  metadata_backend/api/operators.py
  metadata_backend/conf/conf.py
  metadata_backend/conf/schemas.json
  metadata_backend/helpers/parser.py
  metadata_backend/server.py
  setup.py
  tests/integration/run_tests.py
  tests/test_handlers.py
  tests/test_operators.py
  tests/test_parser.py
  tests/test_server.py
Labels: enhancement

#60 Refactor/better error structure
  .github/workflows/docs.yml
  .github/workflows/int.yml
  .github/workflows/publish.yml
  .github/workflows/style.yml
  .github/workflows/unit.yml
  .travis.yml
  README.md
  docs/specification.yml
  metadata_backend/api/handlers.py
  metadata_backend/api/middlewares.py
  metadata_backend/helpers/parser.py
  tests/coveralls.py
  tests/test_handlers.py
  tests/test_middlewares.py
  tox.ini
Labels: enhancement

#64 Feature/add delete and better integration tests
  .github/workflows/int.yml
  Dockerfile
  Dockerfile-dev
  README.md
  development/docker-compose.yml
  development/mongodb-docker/docker-compose.yml
  docker-compose.yml
  docs/specification.yml
  metadata_backend/api/handlers.py
  metadata_backend/api/operators.py
  metadata_backend/conf/conf.py
  metadata_backend/database/db_service.py
  metadata_backend/helpers/parser.py
  metadata_backend/helpers/schema_loader.py
  metadata_backend/server.py
  tests/integration/run_tests.py
  tests/test_handlers.py
  tests/test_middlewares.py
  tests/test_operators.py
Labels: enhancement
