Repository CSCfi/metadata-submitter, pull requests merged in 2020-08, with the labels that each got.

#111 PATCH and DELETE methods for folders
  metadata_backend/api/handlers.py
  metadata_backend/api/operators.py
  metadata_backend/database/db_service.py
  metadata_backend/helpers/validator.py
  metadata_backend/server.py
  requirements.txt
  tests/test_handlers.py
  tests/test_operators.py
Labels: enhancement

#114 Release 0.5.0
  .coveragerc
  .github/workflows/style.yml
  .github/workflows/unit.yml
  CONTRIBUTING.md
  Dockerfile
  README.md
  docs/conf.py
  docs/index.rst
  docs/specification.yml
  docs/validator.rst
  metadata_backend/__init__.py
  metadata_backend/api/handlers.py
  metadata_backend/api/middlewares.py
  metadata_backend/api/operators.py
  metadata_backend/conf/conf.py
  metadata_backend/conf/ena_schemas.json
  metadata_backend/database/db_service.py
  metadata_backend/helpers/logger.py
  metadata_backend/helpers/parser.py
  metadata_backend/helpers/schema_loader.py
  metadata_backend/helpers/schemas/ena_analysis.json
  metadata_backend/helpers/schemas/ena_dac.json
  metadata_backend/helpers/schemas/ena_dataset.json
  metadata_backend/helpers/schemas/ena_experiment.json
  metadata_backend/helpers/schemas/ena_policy.json
  metadata_backend/helpers/schemas/ena_run.json
  metadata_backend/helpers/schemas/ena_sample.json
  metadata_backend/helpers/schemas/ena_study.json
  metadata_backend/helpers/validator.py
  metadata_backend/server.py
  requirements.txt
  setup.py
  tests/conftest.py
  tests/coveralls.py
  tests/integration/run_tests.py
  tests/test_db_service.py
  tests/test_files/analysis/ERZ266973.json
  tests/test_files/experiment/ERX000119.json
  tests/test_files/run/ERR000076.json
  tests/test_files/sample/SRS001433.json
  tests/test_files/sample/put.json
  tests/test_files/study/SRP000539.json
  tests/test_files/study/SRP000539_invalid3.xml
  tests/test_files/study/SRP000539_invalid4.xml
  tests/test_files/study/SRP000539_invalid5.xml
  tests/test_files/study/SRP000539_invalid6.xml
  tests/test_files/study/patch.json
  tests/test_handlers.py
  tests/test_middlewares.py
  tests/test_operators.py
  tests/test_parser.py
  tests/test_schema_loader.py
  tests/test_server.py
  tox.ini
Labels: release

#115 Docker file build fixes
  Dockerfile
Labels: bug

#118 Add folder POST schema
  metadata_backend/api/handlers.py
  metadata_backend/api/operators.py
  metadata_backend/helpers/schemas/folders.json
  tests/test_handlers.py
  tests/test_operators.py
Labels: enhancement

#121 Add user endpoints
  metadata_backend/api/handlers.py
  metadata_backend/api/middlewares.py
  metadata_backend/api/operators.py
  metadata_backend/database/db_service.py
  metadata_backend/helpers/parser.py
  metadata_backend/helpers/schemas/users.json
  metadata_backend/server.py
  tests/test_handlers.py
  tests/test_middlewares.py
  tests/test_operators.py
  tests/test_parser.py
  tests/test_server.py
Labels: enhancement

#127 Update OpenAPI specs
  docs/specification.yml
Labels: documentation

#128 Add python modules to docs
  .gitignore
  docs/_static/style.css
  docs/code.rst
  docs/conf.py
  docs/index.rst
Labels: documentation

#129 Add more integration tests
  .github/workflows/int.yml
  tests/integration/run_tests.py
Labels: enhancement
