Repository CSCfi/metadata-submitter, pull requests merged in 2020-11, with the labels that each got.

#144 Refactor/draft folders
  docs/specification.yml
  metadata_backend/api/handlers.py
  metadata_backend/api/operators.py
  metadata_backend/helpers/schemas/folders.json
  metadata_backend/server.py
  tests/integration/run_tests.py
  tests/test_handlers.py
  tests/test_server.py
Labels: enhancement

#145 bump to 0.6.1
  .github/workflows/docs.yml
  .github/workflows/int.yml
  .github/workflows/publish.yml
  .github/workflows/style.yml
  .github/workflows/unit.yml
  .gitignore
  Dockerfile-dev
  docker-compose.yml
  docs/conf.py
  docs/specification.yml
  metadata_backend/__init__.py
  metadata_backend/api/auth.py
  metadata_backend/api/handlers.py
  metadata_backend/api/middlewares.py
  metadata_backend/api/operators.py
  metadata_backend/conf/conf.py
  metadata_backend/helpers/logger.py
  metadata_backend/helpers/schemas/folders.json
  metadata_backend/server.py
  requirements.txt
  tests/integration/run_tests.py
  tests/test_handlers.py
  tests/test_server.py
Labels: release

#150 check idp starts with
  metadata_backend/api/middlewares.py
  tests/test_operators.py
Labels: bug
