Repository CSCfi/metadata-submitter, pull requests merged in 2020-05, with the labels that each got.

#1 Add license
  LICENSE
Labels: documentation

#3 Add GitHub templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/general-issue-template.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#2 Add contributing guidelines
  CONTRIBUTING.md
Labels: documentation

#5 Bugfix/package path
  metadata_backend/api/views.py
  metadata_backend/helpers/schema_load.py
  metadata_backend/server.py
  tests/test_utils.py
Labels: bug

#12 Feature/add tox configs tests and fixes
  .travis.yml
  Dockerfile
  metadata_backend/api/parser.py
  metadata_backend/api/translator.py
  metadata_backend/api/views.py
  metadata_backend/database/db_services.py
  metadata_backend/server.py
  requirements.txt
  scripts/install-hooks.bash
  scripts/pre-commit.bash
  setup.py
  tests/__init__.py
  tests/api/test_views.py
  tests/conftest.py
  tests/coveralls.py
  tests/test_files/submission/ERA521986.xml
  tests/test_files/submission/ERA521986_emptyhold.xml
  tests/test_files/submission/ERA521986_nodetails.xml
  tests/test_files/submission/ERA521986_valid.xml
  tests/test_files/submission/ERA521986_valid2.xml
  tests/test_helpers.py
  tests/test_server.py
  tox.ini
Labels: enhancement
