Repository CSCfi/metadata-submitter, pull requests merged in 2020-07, with the labels that each got.

#62 Feature/add better xml parsing
  metadata_backend/conf/conf.py
  metadata_backend/helpers/parser.py
  tests/test_operators.py
  tests/test_parser.py
  tox.ini
Labels: enhancement

#68 Create release 0.2.0
  .github/workflows/docs.yml
  .github/workflows/int.yml
  .github/workflows/publish.yml
  .github/workflows/style.yml
  .github/workflows/unit.yml
  .gitignore
  .travis.yml
  CONTRIBUTING.md
  Dockerfile
  Dockerfile-dev
  README.md
  deploy/app.sh
  deploy/mongodb/docker-compose.yml
  docker-compose.yml
  docs/Makefile
  docs/_static/style.css
  docs/conf.py
  docs/index.rst
  docs/specification.yml
  metadata_backend/__init__.py
  metadata_backend/api/handlers.py
  metadata_backend/api/middlewares.py
  metadata_backend/api/operators.py
  metadata_backend/conf/conf.py
  metadata_backend/conf/schemas.json
  metadata_backend/database/db_service.py
  metadata_backend/helpers/parser.py
  metadata_backend/helpers/schema_loader.py
  metadata_backend/server.py
  requirements.txt
  setup.py
  tests/coveralls.py
  tests/integration/run_tests.py
  tests/test_files/study/SRP000539_copy.xml
  tests/test_files/study/SRP000539_invalid2.xml
  tests/test_handlers.py
  tests/test_middlewares.py
  tests/test_operators.py
  tests/test_parser.py
  tests/test_server.py
  tox.ini
Labels: release

#78 fix XML etree import warning for safer XML parsing
  metadata_backend/api/handlers.py
  metadata_backend/helpers/parser.py
Labels: bug

#82 Docs/add validator cli docs
  docs/index.rst
  docs/validator.rst
Labels: documentation

#90 Bugfix/urlib path error
  metadata_backend/api/handlers.py
  metadata_backend/helpers/parser.py
  tests/test_handlers.py
Labels: bug

#88 Fix error: xml validation error details
  metadata_backend/api/handlers.py
  tests/test_files/study/SRP000539_invalid3.xml
  tests/test_files/study/SRP000539_invalid4.xml
  tests/test_files/study/SRP000539_invalid5.xml
  tests/test_files/study/SRP000539_invalid6.xml
  tests/test_handlers.py
Labels: bug

#93 Refactor: Extract validation error handling to different module
  metadata_backend/api/handlers.py
  metadata_backend/helpers/parser.py
  metadata_backend/helpers/validator.py
  tests/test_parser.py
Labels: enhancement

#100 Bugfix integer parameter query and filetype
  metadata_backend/api/operators.py
  metadata_backend/conf/conf.py
  metadata_backend/helpers/parser.py
  metadata_backend/helpers/schemas/ena_analysis.json
  metadata_backend/helpers/schemas/ena_run.json
  tests/integration/run_tests.py
  tests/test_parser.py
Labels: bug

#95 Add authentication/authorization middleware
  metadata_backend/api/middlewares.py
  metadata_backend/server.py
  requirements.txt
  tests/test_middlewares.py
Labels: enhancement

#99 Add draft submission feature
  .coveragerc
  metadata_backend/api/handlers.py
  metadata_backend/api/operators.py
  metadata_backend/database/db_service.py
  metadata_backend/server.py
  tests/integration/run_tests.py
  tests/test_db_service.py
  tests/test_files/analysis/ERZ266973.json
  tests/test_files/experiment/ERX000119.json
  tests/test_files/run/ERR000076.json
  tests/test_files/sample/SRS001433.json
  tests/test_files/study/SRP000539.json
  tests/test_handlers.py
  tests/test_operators.py
  tests/test_server.py
Labels: enhancement

#101 Add folder creation endpoint
  metadata_backend/api/handlers.py
  metadata_backend/database/db_service.py
  metadata_backend/server.py
  tests/test_db_service.py
  tests/test_handlers.py
  tests/test_server.py
Labels: enhancement

#104 Add folder get methods
  metadata_backend/api/handlers.py
  metadata_backend/api/middlewares.py
  metadata_backend/conf/conf.py
  metadata_backend/database/db_service.py
  metadata_backend/helpers/parser.py
  metadata_backend/helpers/schema_loader.py
  metadata_backend/helpers/validator.py
  tests/integration/run_tests.py
  tests/test_db_service.py
  tests/test_handlers.py
  tests/test_middlewares.py
  tests/test_operators.py
  tests/test_parser.py
  tests/test_schema_loader.py
  tests/test_server.py
  tox.ini
Labels: enhancement
