Repository CSCfi/metadata-submitter, pull requests merged in 2021-08, with the labels that each got.

#231 Folder, draft and draft template pagination
  docs/specification.yml
  docs/test.rst
  locust.conf
  metadata_backend/api/handlers.py
  metadata_backend/api/operators.py
  tests/integration/run_tests.py
  tests/performance/locustfile.py
  tests/test_handlers.py
  tests/test_operators.py
Labels: enhancement

#225 release 0.10.0
  .github/workflows/int.yml
  .gitignore
  Dockerfile
  docs/_static/metadata-app.svg
  docs/_static/metadata-model.svg
  docs/conf.py
  docs/index.rst
  docs/metadata.rst
  docs/specification.yml
  docs/submitter.rst
  docs/test.rst
  locust.conf
  metadata_backend/__init__.py
  metadata_backend/api/handlers.py
  metadata_backend/api/middlewares.py
  metadata_backend/api/operators.py
  metadata_backend/conf/ena_schemas.json
  metadata_backend/helpers/parser.py
  metadata_backend/helpers/schemas/EGA.dac.xsd
  metadata_backend/helpers/schemas/EGA.dataset.xsd
  metadata_backend/helpers/schemas/EGA.policy.xsd
  metadata_backend/helpers/schemas/ENA.assembly.xsd
  metadata_backend/helpers/schemas/ENA.checklist.xsd
  metadata_backend/helpers/schemas/ENA.project.xsd
  metadata_backend/helpers/schemas/SRA.analysis.xsd
  metadata_backend/helpers/schemas/SRA.common.xsd
  metadata_backend/helpers/schemas/SRA.experiment.xsd
  metadata_backend/helpers/schemas/SRA.receipt.xsd
  metadata_backend/helpers/schemas/SRA.run.xsd
  metadata_backend/helpers/schemas/SRA.sample.xsd
  metadata_backend/helpers/schemas/SRA.study.xsd
  metadata_backend/helpers/schemas/SRA.submission.xsd
  metadata_backend/helpers/schemas/ena_analysis.json
  metadata_backend/helpers/schemas/ena_dac.json
  metadata_backend/helpers/schemas/ena_dataset.json
  metadata_backend/helpers/schemas/ena_experiment.json
  metadata_backend/helpers/schemas/ena_policy.json
  metadata_backend/helpers/schemas/ena_run.json
  metadata_backend/helpers/schemas/ena_sample.json
  metadata_backend/helpers/schemas/ena_study.json
  requirements.txt
  scripts/extfile.ext
  scripts/tls_helper.sh
  setup.py
  tests/integration/clean_db.py
  tests/integration/run_tests.py
  tests/performance/locustfile.py
  tests/test_files/analysis/ERZ266973.json
  tests/test_files/analysis/ERZ266973.xml
  tests/test_files/dac/dac.xml
  tests/test_files/dataset/dataset.xml
  tests/test_files/experiment/paired.xml
  tests/test_files/experiment/sample_description.xml
  tests/test_files/policy/policy.xml
  tests/test_files/run/ERR000076.json
  tests/test_files/run/ERR000076.xml
  tests/test_handlers.py
  tests/test_operators.py
  tests/test_parser.py
  tox.ini
Labels: release

#249 Feature/sort folders
  .github/workflows/style.yml
  metadata_backend/api/handlers.py
  metadata_backend/api/operators.py
  metadata_backend/database/db_service.py
  metadata_backend/helpers/schemas/folders.json
  tests/test_db_service.py
  tests/test_handlers.py
  tests/test_operators.py
  tox.ini
Labels: bug, enhancement

#246 Include DOI information in the folder schema
  docs/specification.yml
  metadata_backend/api/handlers.py
  metadata_backend/helpers/schemas/folders.json
  tests/integration/run_tests.py
  tests/test_files/doi/test_doi.json
Labels: enhancement

#252 Release 0.11.0
  .github/workflows/style.yml
  Dockerfile
  docs/conf.py
  docs/specification.yml
  metadata_backend/__init__.py
  metadata_backend/api/handlers.py
  metadata_backend/api/operators.py
  metadata_backend/database/db_service.py
  metadata_backend/helpers/schemas/folders.json
  requirements.txt
  setup.py
  tests/integration/run_tests.py
  tests/test_db_service.py
  tests/test_files/doi/test_doi.json
  tests/test_handlers.py
  tests/test_operators.py
  tox.ini
Labels: release
