Repository CSCfi/metadata-submitter, pull requests merged in 2022-05, with the labels that each got.

#420 Fix/tls database connection
  .env.example
  .github/config/.wordlist.txt
  .github/workflows/int.yml
  CHANGELOG.md
  docker-compose-tls.yml
  docs/submitter.rst
  metadata_backend/conf/conf.py
  tests/integration/clean_db.py
  tests/integration/mongo_indexes.py
  tests/integration/run_tests.py
  tests/test_conf.py
Labels: bug

#434 Refactor folder -> submission
  .github/config/.wordlist.txt
  CHANGELOG.md
  docs/frontend.rst
  docs/specification.yml
  docs/submitter.rst
  docs/test.rst
  metadata_backend/api/handlers/folder.py
  metadata_backend/api/handlers/object.py
  metadata_backend/api/handlers/restapi.py
  metadata_backend/api/handlers/submission.py
  metadata_backend/api/handlers/template.py
  metadata_backend/api/handlers/user.py
  metadata_backend/api/handlers/xml_submission.py
  metadata_backend/api/middlewares.py
  metadata_backend/api/operators.py
  metadata_backend/database/db_service.py
  metadata_backend/helpers/metax_mapper.py
  metadata_backend/helpers/schemas/submissions.json
  metadata_backend/server.py
  scripts/init_mongo.js
  tests/http/publication_minimal.http
  tests/integration/mongo_indexes.py
  tests/integration/run_tests.py
  tests/performance/locustfile.py
  tests/test_db_service.py
  tests/test_files/analysis/reference_alignment_analysis.xml
  tests/test_handlers.py
  tests/test_operators.py
  tests/test_server.py
Labels: technical dept

#431 Add swagger endpoint and generation script.
  CHANGELOG.md
  Dockerfile
  metadata_backend/api/handlers/static.py
  metadata_backend/api/middlewares.py
  metadata_backend/conf/conf.py
  metadata_backend/server.py
  requirements-dev.in
  requirements-dev.txt
  scripts/swagger/generate.sh
  scripts/swagger/yaml-to-html.py
  setup.py
  tests/test_server.py
Labels: documentation, enhancement
