Repository CSCfi/metadata-submitter, pull requests merged in 2022-06, with the labels that each got.

#433 HTTPError exceptions return a JSON Problem instead of HTML.
  .github/config/.wordlist.txt
  CHANGELOG.md
  docs/specification.yml
  metadata_backend/api/middlewares.py
Labels: technical debt

#477 Recreate db schema before integration tests.
  CHANGELOG.md
  Procfile
  tests/integration/clean_db.py
  tests/integration/mock_metax_api.py
  tests/integration/mongo.py
  tests/integration/mongo_indexes.py
  tests/integration/run_tests.py
Labels: technical debt

#482 Share code between service handlers.
  .github/config/.wordlist.txt
  CHANGELOG.md
  metadata_backend/api/handlers/object.py
  metadata_backend/api/handlers/submission.py
  metadata_backend/api/handlers/xml_submission.py
  metadata_backend/helpers/doi.py
  metadata_backend/services/__init__.py
  metadata_backend/services/datacite_service_handler.py
  metadata_backend/services/metax_mapper.py
  metadata_backend/services/metax_service_handler.py
  metadata_backend/services/retry.py
  metadata_backend/services/service_handler.py
  tests/http/publication_minimal.http
  tests/test_doi.py
  tests/test_handlers.py
Labels: enhancement, technical debt

#493 Fix/datacite missing study doi
  metadata_backend/api/handlers/submission.py
  tests/integration/mock_doi_api.py
  tests/integration/run_tests.py
Labels: bug

#499 Feature/map relations metadata for metax
  metadata_backend/api/handlers/submission.py
  metadata_backend/services/metax_mapper.py
  metadata_backend/services/metax_service_handler.py
  tests/integration/run_tests.py
Labels: Metax integration
