Repository CSCfi/metadata-submitter, pull requests merged in 2022-09, with the labels that each got.

#566 Add Github action to combine dependabot PRs.
  .github/workflows/combine-dependabot-prs.yml
Labels: github actions

#580 add support for LSAAI groups #548
  CHANGELOG.md
  docs/dictionary/wordlist.txt
  metadata_backend/api/auth.py
  tests/integration/mock_auth.py
  tests/unit/test_auth.py
Labels: enhancement

#595 Merge master into develop
  .github/ISSUE_TEMPLATE/user_story.md
  .github/dependabot.yml
  CHANGELOG.md
  docs/dictionary/wordlist.txt
Labels: technical debt

#597 Refactor/logging fmt
  .pylintrc
  CHANGELOG.md
  docs/dictionary/wordlist.txt
  metadata_backend/api/auth.py
  metadata_backend/api/handlers/common.py
  metadata_backend/api/handlers/object.py
  metadata_backend/api/handlers/restapi.py
  metadata_backend/api/handlers/static.py
  metadata_backend/api/handlers/submission.py
  metadata_backend/api/handlers/template.py
  metadata_backend/api/handlers/user.py
  metadata_backend/api/handlers/xml_submission.py
  metadata_backend/api/health.py
  metadata_backend/api/middlewares.py
  metadata_backend/api/operators.py
  metadata_backend/conf/conf.py
  metadata_backend/database/db_service.py
  metadata_backend/helpers/logger.py
  metadata_backend/helpers/parser.py
  metadata_backend/helpers/validator.py
  metadata_backend/server.py
  metadata_backend/services/datacite_service_handler.py
  metadata_backend/services/metax_mapper.py
  metadata_backend/services/metax_service_handler.py
  metadata_backend/services/rems_service_handler.py
  metadata_backend/services/retry.py
  metadata_backend/services/service_handler.py
  scripts/metax_mappings/create_metax_references.py
  tests/integration/helpers.py
  tests/integration/mock_doi_api.py
  tests/integration/mock_metax_api.py
  tests/unit/test_handlers.py
Labels: technical debt
